<?php

namespace NCMF\UserBundle\Repository;

/**
 * UserInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
